apiVersion: v1
kind: Service
metadata:
  name: cache-app-service
  labels:
    app: cache-app
spec:
  type: ClusterIP 
  selector:
    app: cache-app
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080 