apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-app
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: app
        env:
        - name: PROJECT_ID
          value: "${GCP_PROJECT_ID}"
        - name: DB_USER
          value: "${DB_USER}"
        - name: DB_NAME
          value: "${DB_NAME}"
        - name: DB_INSTANCE_CONNECTION_NAME
          value: "${DB_INSTANCE_CONNECTION_NAME}"
        - name: PUBSUB_TOPIC_ID
          value: "${PUBSUB_TOPIC_ID}"
        - name: DB_PASSWORD_SECRET_ID
          value: "db-password"