# Placeholder for production deployment patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-app # Must match the base deployment name
spec:
  replicas: 1 # Set desired replicas for production (Reduced from 4)
  template:
    spec:
      containers:
      - name: app
        env:
          - name: GCLOUD_PROJECT_ID
            value: "${GCP_PROJECT_ID}" # Will be replaced by CI/CD
          - name: DB_USER
            value: "${DB_USER}" # Will be replaced by CI/CD
          - name: DB_NAME
            value: "${DB_NAME}" # Will be replaced by CI/CD
          - name: DB_INSTANCE_CONNECTION_NAME
            value: "${DB_INSTANCE_CONNECTION_NAME}" # Will be replaced by CI/CD
          - name: PUBSUB_TOPIC_ID
            value: "${PUBSUB_TOPIC_ID}" # Will be replaced by CI/CD