# Placeholder for production deployment patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-app # Must match the base deployment name
spec:
  replicas: 4 # Set desired replicas for production
  template:
    spec:
      containers:
      - name: app
        env:
          - name: GCLOUD_PROJECT_ID
            value: "${GCP_PROJECT_ID}" # Will be replaced by CI/CD
          - name: DB_USER
            value: "${DB_USER}" # Will be replaced by CI/CD
          - name: DB_NAME
            value: "${DB_NAME}" # Will be replaced by CI/CD
          - name: DB_INSTANCE_CONNECTION_NAME
            value: "${DB_INSTANCE_CONNECTION_NAME}" # Will be replaced by CI/CD
          - name: PUBSUB_TOPIC_ID
            value: "${PUBSUB_TOPIC_ID}" # Will be replaced by CI/CD
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                # This name should match the Secret created by Terraform/manually
                # It's kept consistent across environments here, but could be patched differently
                name: ${DB_PASSWORD_SECRET_ID} # Use placeholder
                key: password